//! Auto-solver for Helldivers 1's directional interact-combo mini-game
//! (terminal panels, mine/UXO defuse, "brute force = detonation" objects).
//!
//! No hardcoded combo and no screen-reading (both were dead ends — see
//! `AUTO_COMBO_PLAN.md`): the combo is generated by the game itself from a
//! small integer `seed` via a Numerical-Recipes LCG
//! (`s' = s*1664525 + 1013904223 mod 2^32`, draw = `floor(u*4)` with
//! `u = s'/2^32`, `0=left 1=up 2=right 3=down`) — reverse-engineered from the
//! native `Math.next_random` binding (`sub_140100FC180` in `helldivers.exe`)
//! and validated live against two independent activations, both reproducing
//! the on-screen arrows exactly.
//!
//! **Scope (this version): mines/UXO only.** Detection keys on a per-type
//! marker (`0xCF` at `anchor+0x18`) that's specific to the hidden-sweep/mine
//! component. A *universal* detector (rocket/SAM, terminals, …) can't be done
//! by a static scan — the shared field structure alone matches thousands of
//! coincidental spots (`interacting=4/5` etc.), and there's no per-type marker
//! that generalizes; that needs a pointer-anchor from the interaction manager
//! (a documented follow-on, see `AUTO_COMBO_PLAN.md`). Mines are the
//! high-stakes case (wrong input detonates), so this precise, safe detector is
//! the one that ships.
//!
//! `solve` never needs the combo's total length: it derives the next direction
//! from the *live* `progress` each iteration and stops the moment the window
//! closes (`interacting_unit` clears) — see its doc comment.

use std::time::Duration;

use n0xis_arch::X64;
use n0xis_contracts::Va;
use n0xis_core::{parse_aob, AobInput, AobScanPass, Ctx, Pass};
use n0xis_luajit::Lcg;
use n0xis_sources::{LiveProcess, MemorySource};

use crate::interception::KeySender;

/// The mine component's type marker (`0x000000CF`, `0x00000001` at
/// `anchor+0x18`/`+0x1c`), confirmed invariant across three independent live
/// mine instances. Too weak alone (an 8-byte mostly-zero pattern matches
/// unaligned coincidences), so [`find_candidates_in`] additionally requires
/// 4-byte alignment, an open window, and a uint31-scale seed. The component's
/// fields, relative to the marker's `anchor`:
///
///   anchor+0x24  progress       0..combo-length
///   anchor+0x28  interacting    0xFFFF when no window open, else a unit handle
///   anchor+0x2c  seed           the uint31 the combo is generated from
const SIGNATURE: &str = "cf 00 00 00 01 00 00 00";
const SIG_OFFSET: u64 = 0x18;
/// The `interacting_unit` handle (Lua `state.interacting_unit`): `0xFFFF` when
/// nobody is at this object, else a real unit handle while its combo window is
/// open. The one reliable "is this the window on screen right now" flag —
/// confirmed live by a close→open diff moving *only* this dword, `0xFFFF` → a
/// handle. (`state` is not usable: it reads `0` for an active mine but `1` for
/// an active rocket, and an abandoned object keeps its state.)
const INTERACTING_OFFSET: u64 = 0x28;
const INTERACTING_NONE: u32 = 0xFFFF;
const PROGRESS_OFFSET: u64 = 0x24;
const SEED_OFFSET: u64 = 0x2c;

/// The exact constants `Math.next_random` uses (decompiled from
/// `sub_140100FC180`).
const LCG: Lcg = Lcg { a: 1_664_525, c: 1_013_904_223 };
/// `random(0,3)` draw → direction, from `modify_random_combo_inputs`.
const DIRS: [&str; 4] = ["left", "up", "right", "down"];

/// One live interact-combo component (any type).
#[derive(Debug, Clone, Copy)]
pub struct Candidate {
    pub anchor: Va,
    pub progress: u32,
    pub seed: u32,
    /// True when its combo window is currently open (`interacting != 0xFFFF`) —
    /// only these are ever solved.
    pub window_open: bool,
}

fn direction_at(seed: u32, index: usize) -> &'static str {
    // Draws are independent of one another given the seed (each is a fresh
    // LCG step from the *original* seed's fixed sequence), so regenerating
    // up to `index` every call is correct and needs no mutable RNG state.
    let seq = LCG.range_seq(seed, 4, index + 1);
    DIRS[seq[index] as usize]
}

fn scan_regions(live: &LiveProcess, regions: &[(Va, usize)]) -> Result<Vec<Va>, String> {
    let parsed = parse_aob(SIGNATURE)?;
    let arch = X64::new();
    let ctx = Ctx::new(live, &arch);
    let mut matches = Vec::new();
    for &(start, size) in regions {
        // A region enumerated a moment ago can be unmapped by the time we read
        // it — the game constantly allocates/frees during play, so a live
        // range list is racy by nature. **Skip** a region that fails to read
        // rather than aborting the whole scan: one transiently-freed page must
        // not sink the whole detection pass (this is exactly what made the
        // background solver silently catch nothing — see AUTO_COMBO_PLAN.md's
        // "not mapped" note). The next poll re-scans anyway.
        if let Ok(art) = AobScanPass.run(&ctx, AobInput { start, size, pattern: parsed.clone() }) {
            matches.extend(art.matches);
        }
    }
    Ok(matches)
}

/// The committed writable region containing `addr`, as `(base, size)` — used to
/// cache the mine-component pool's region so steady-state polls scan only it
/// (kilobytes) instead of the whole writable address space (gigabytes).
pub fn containing_region(live: &LiveProcess, addr: Va) -> Option<(Va, usize)> {
    live.default_writable_regions().into_iter().find(|&(base, size)| base <= addr && addr.0 < base.0 + size as u64)
}

fn read_u32(live: &LiveProcess, addr: Va) -> Option<u32> {
    let b = live.read(addr, 4).ok()?;
    Some(u32::from_le_bytes(b.get(..4)?.try_into().ok()?))
}

/// A real seed comes from `math.random(1, 2^31-2)` (see
/// `modify_random_combo_inputs`'s `state.seed` generation) — uniformly
/// spread across a 31-bit range, so a genuine draw landing under this floor
/// has probability ~1 in 21500. A coincidental byte-pattern match in
/// unrelated data, by contrast, overwhelmingly lands on small/round values
/// (confirmed live: bogus hits read `seed=1`, `seed=47`, `seed=209`, `seed=0`
/// — nothing close to uint31-scale). This floor is what separates them; see
/// `SIGNATURE`'s doc comment for the alignment half of the filter.
const SEED_FLOOR: u32 = 100_000;

fn plausible_seed(seed: u32) -> bool {
    (SEED_FLOOR..=0x7FFF_FFFE).contains(&seed)
}

/// Find live mine components across the whole writable address space (there may
/// be several resident at once — active, defused, failed). Only ones with an
/// open window are returned.
pub fn find_candidates(live: &LiveProcess) -> Result<Vec<Candidate>, String> {
    find_candidates_in(live, &live.default_writable_regions())
}

/// Like [`find_candidates`] but restricted to `regions` — pass the cached pool
/// region for a fast steady-state poll, or the full writable set to discover a
/// pool for the first time (or after it relocates).
pub fn find_candidates_in(live: &LiveProcess, regions: &[(Va, usize)]) -> Result<Vec<Candidate>, String> {
    let hits = scan_regions(live, regions)?;
    let mut out = Vec::new();
    for hit in hits {
        if hit.0 % 4 != 0 {
            continue;
        }
        let anchor = Va(hit.0.saturating_sub(SIG_OFFSET));
        let (Some(interacting), Some(progress), Some(seed)) = (
            read_u32(live, anchor.offset(INTERACTING_OFFSET)),
            read_u32(live, anchor.offset(PROGRESS_OFFSET)),
            read_u32(live, anchor.offset(SEED_OFFSET)),
        ) else {
            continue;
        };
        // Return every resident mine (open or not) so the caller can cache the
        // pool's region even while idle; it solves only the `window_open` one.
        // That matters because all keyboard input goes to the single open
        // window — replaying any other resident mine's combo would be the wrong
        // input, i.e. a detonation.
        if plausible_seed(seed) {
            out.push(Candidate { anchor, progress, seed, window_open: interacting != INTERACTING_NONE });
        }
    }
    Ok(out)
}

/// Outcome of a solve attempt, carrying the exact directions tapped (for the
/// "which keys were pressed" log the HUD shows).
pub enum SolveOutcome {
    /// The window closed / objective resolved (solved, or the player walked
    /// off) — the normal, clean end.
    Done { keys: Vec<&'static str> },
    /// Stopped early for a reason worth surfacing (a wrong-input reset, or the
    /// safety cap) — still reports what it had sent.
    Aborted { reason: String, keys: Vec<&'static str> },
}

impl SolveOutcome {
    pub fn keys(&self) -> &[&'static str] {
        match self {
            SolveOutcome::Done { keys } | SolveOutcome::Aborted { keys, .. } => keys,
        }
    }
}

/// Drive the open window to completion: each iteration, tap the direction the
/// game expects next (`direction_at(seed, live progress)`), then confirm
/// `progress` advanced.
///
/// **Stops exactly at the end — no stray taps.** It re-reads `interacting_unit`
/// at the top of every iteration and bails the instant the window is no longer
/// open (completion clears `interacting_unit` on the same frame it writes the
/// final `progress`). That's what fixes the "kept pressing keys after it was
/// already solved" bug: the old code didn't know the combo length, so it tapped
/// a few extra "just in case" times past the end — which, on a fresh window,
/// would be *wrong* directions. It keys on `interacting_unit`, **not** `state`,
/// because `state`'s active value differs by object type (mine `0`, rocket
/// `1`) while the empty-handle sentinel is universal. It also never needs the
/// combo length (4-step terminals and 8-step mines both just work).
pub fn solve(live: &LiveProcess, sender: &KeySender, start: Candidate, max_steps: u32) -> SolveOutcome {
    const MAX_STALLS: u32 = 3;
    const RECHECK_DELAY: Duration = Duration::from_millis(120);

    let mut progress = start.progress;
    let mut stalls = 0u32;
    let mut keys: Vec<&'static str> = Vec::new();

    while (keys.len() as u32) < max_steps {
        // Window still open? Checking BEFORE the tap means the last correct
        // input (which completes the objective and closes the window) is never
        // followed by a stray one.
        match read_u32(live, start.anchor.offset(INTERACTING_OFFSET)) {
            Some(i) if i == INTERACTING_NONE => return SolveOutcome::Done { keys }, // window closed
            None => return SolveOutcome::Done { keys },                             // component gone
            _ => {}
        }

        // Live progress is the source of truth for which direction is next.
        if let Some(p) = read_u32(live, start.anchor.offset(PROGRESS_OFFSET)) {
            if p == 0 && progress > 0 {
                return SolveOutcome::Aborted { reason: "progress reset to 0 (wrong input?)".into(), keys };
            }
            progress = p;
        }

        let dir = direction_at(start.seed, progress as usize);
        sender.tap(dir);
        keys.push(dir);
        std::thread::sleep(RECHECK_DELAY);

        match read_u32(live, start.anchor.offset(PROGRESS_OFFSET)) {
            Some(p) if p > progress => {
                progress = p;
                stalls = 0;
            }
            None => return SolveOutcome::Done { keys }, // component gone: solved & torn down
            _ => {
                stalls += 1;
                if stalls >= MAX_STALLS {
                    return SolveOutcome::Aborted { reason: "progress stopped advancing".into(), keys };
                }
            }
        }
    }
    SolveOutcome::Aborted { reason: format!("hit the {max_steps}-step safety cap"), keys }
}
