#!/usr/bin/env bash
# Reproduce the committed OSS signature samples from pinned upstream sources.
#
# Each corpus is built from its published source at a pinned tag and fingerprinted
# by `n0xis sig gen`, so the provenance is this script rather than an opaque blob.
# Only OSS libraries whose license permits redistribution belong here — see
# README.md for what may and may not be added.
#
# Usage:  signatures/generate.sh [output-dir]      (default: signatures/samples)
set -euo pipefail

here="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
out="${1:-$here/samples}"
work="$(mktemp -d)"
trap 'rm -rf "$work"' EXIT
mkdir -p "$out"

# Locate the n0xis binary (release build preferred, else on PATH).
n0xis="$here/../target/release/n0xis"
[ -x "$n0xis" ] || n0xis="$(command -v n0xis)"

# --- zlib ---------------------------------------------------------------------
# Shared, PIC build of the v1.3.1 release; the corpus therefore matches PIC/PIE
# targets that statically link zlib 1.3.1.
zlib_tag="v1.3.1"
git clone --depth 1 --branch "$zlib_tag" https://github.com/madler/zlib "$work/zlib"
( cd "$work/zlib" && CHOST=x86_64-pc-linux-gnu ./configure >/dev/null && make -j"$(nproc)" >/dev/null )
so="$work/zlib/libz.so.1.3.1"
hdr="# zlib 1.3.1 (x86-64, gcc -O2 -fPIC, shared libz.so.1.3.1)
# Generated by \`n0xis sig gen\` from a from-source build of zlib $zlib_tag.
# Source: https://github.com/madler/zlib  tag $zlib_tag  License: zlib (see ../NOTICE)
# NOT derived from any other tool's shipped signatures. See ../README.md."
{
  printf '%s\n' "$hdr"
  # sig gen emits its own machine-path header line; drop it and keep the patterns.
  "$n0xis" sig gen --file "$so" \
    | python3 -c 'import sys,json; print(json.load(sys.stdin)["data"]["npat"], end="")' \
    | grep -v '^# n0xis n0xis.sig.gen.v1 signatures generated from'
} > "$out/zlib-1.3.1-x86_64.npat"
echo "wrote $out/zlib-1.3.1-x86_64.npat"

# --- add more OSS libraries here (OpenSSL/Apache-2.0, Qt/LGPL, …) --------------
# Follow the same pattern: pin a tag, build from source, sig gen, and add the
# upstream license to NOTICE. Do NOT add proprietary-library corpora (MSVC CRT):
# those stay generate-locally per README.md.
